name: dynamic_cached_fonts
description: A font loader to download, cache and load web fonts in flutter with support for Firebase Cloud Storage.
version: 1.0.0
repository: https://github.com/sidrao2006/dynamic_cached_fonts

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  path_provider: ^2.0.2

dev_dependencies:
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter
